version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    env_file:
      - ./config/.env.develop
    depends_on:
      - mysql
      - mysql-test
      - redis
    links:
      - mysql
      - mysql-test
      - redis
    command: /app/bin

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ./config/.env.develop

  mysql-test:
    image: mysql:8.0
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: mydb_test
    ports:
      - '3307:3306'

  redis:
    image: redis:6.2
    container_name: redis
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    volumes:
      - red_data:/var/lib/redis
    ports:
      - 6379:6379

volumes:
  mysql_data: {}
  red_data: {}
